name: Build & Upload to Cloudsmith

# 👉 Run automatically on every push to main (change if you like)
on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Pull project code
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣  Use the Python version you need
      - name: Set-up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣  Install build tools + twine
      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      # 4️⃣  Build wheel + sdist into dist/
      - name: Build package
        run: python setup.py sdist bdist_wheel

      # 5️⃣  Upload every file in dist/ to Cloudsmith
      - name: Upload to Cloudsmith with Twine
        env:
          TWINE_USERNAME: rini-jain
          TWINE_PASSWORD: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          twine upload \
            --repository-url https://python.cloudsmith.io/rini-jain-rnye/api_repo/ \
            dist/*
