name: Upload Python Package to Cloudsmith via CLI

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Install dependencies
      - name: Install build tools and Cloudsmith CLI
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel cloudsmith-cli

      # 4️⃣ Build your package
      - name: Build Python package
        run: |
          python setup.py bdist_wheel

      # 5️⃣ Upload to Cloudsmith using CLI
      - name: Push to Cloudsmith
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          cloudsmith push python rini-jain-rnye/api_repo dist/*.whl
